[project]
name = "agent_ui"
version = "0.1.0"
description = "LangGraph-based dataset agent with supervisor"
dependencies = []

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
